jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}
    refresh: ${JWT_REFRESH_SECRET}


server:
  port: 8080

spring:
  profiles:
    active: prod

---
spring:
  application:
    name: authService
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false

logging:
  level:
    org: info
    com: off
    com.netflix.discovery: warn
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: error

---
spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true
    hostname: localhost