spring:
  application:
    name: forgotPasswordService
  security:
    jwt:
      secret: ${JWT_SECRET}
  profiles:
    active: prod
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}
    refresh: ${JWT_REFRESH_SECRET}

server:
  port: 8080

logging:
  level:
    root: info
    com.netflix.discovery: warn
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: error

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
