spring:
  application:
    name: fileService
  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: ${FILE_SERVICE_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


salt: ${SALT}

