spring:
  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
salt: ${SALT}