spring:
  application:
    name: notificationService
  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost


salt: ${SALT}

emailService:
  url: http://localhost:8080/emailservice

server:
  port: ${NOTIFICATION_SERVICE_PORT}
