spring:
  application:
    name: notificationService
  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


salt: ${SALT}

server:
  port: ${NOTIFICATION_SERVICE_PORT}
