spring:
  application:
    name: notificationService
  datasource:
    url: jdbc:postgresql://localhost:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true
    hostname: localhost


salt: ${SALT}

emailService:
  url: ${EMAIL_SERVICE_URL}

server:
  port: ${NOTIFICATION_SERVICE_PORT}