spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            exposed-headers:
              - Authorization
              - Content-Type
              - Access-Control-Allow-Origin
            allow-credentials: true

      discovery:
        locator:
          enabled: true    # Автоматичне визначення сервісів у Eureka
          lower-case-service-id: true

      routes:

        - id: fileservice
          uri: lb://fileservice
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=1

        - id: emailservice
          uri: lb://emailservice
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=1

        - id: notificationservice
          uri: lb://notificationservice
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

        - id: statementservice
          uri: lb://statementservice
          predicates:
            - Path=/api/statements/**
          filters:
            - StripPrefix=1

        - id: forgotpasswordservice
          uri: lb://forgotpasswordservice
          predicates:
            - Path=/api/forgot-password/**
          filters:
            - StripPrefix=1

        - id: authservice
          uri: lb://authservice
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8080
